local LSM3 = LibStub("LibSharedMedia-3.0", true)
local LSM2 = LibStub("LibSharedMedia-2.0", true)
local SML = LibStub("SharedMedia-1.0", true)

local LSM3 = LibStub("LibSharedMedia-3.0", true)
local LSM2 = LibStub("LibSharedMedia-2.0", true)
local SML = LibStub("SharedMedia-1.0", true)

Aijson = {}

Aijson.registry = { ["font"] = {} }

function Aijson:Register(mediatype, key, data, langmask)
	if LSM3 then
		LSM3:Register(mediatype, key, data, langmask)
	end
	if LSM2 then
		LSM2:Register(mediatype, key, data)
	end
	if SML then
		SML:Register(mediatype, key, data)
	end
	if not Aijson.registry[mediatype] then
		Aijson.registry[mediatype] = {}
	end
	table.insert(Aijson.registry[mediatype], { key, data, langmask})
end

function Aijson.OnEvent(this, event, ...)
	if not LSM3 then
		LSM3 = LibStub("LibSharedMedia-3.0", true)
		if LSM3 then
			for m,t in pairs(Aijson.registry) do
				for _,v in ipairs(t) do
					LSM3:Register(m, v[1], v[2], v[3])
				end
			end
		end
	end
	if not LSM2 then
		LSM2 = LibStub("LibSharedMedia-2.0", true)
		if LSM2 then
			for m,t in pairs(Aijson.registry) do
				for _,v in ipairs(t) do
					LSM2:Register(m, v[1], v[2])
				end
			end
		end
	end
	if not SML then
		SML = LibStub("SharedMedia-1.0", true)
		if SML then
			for m,t in pairs(Aijson.registry) do
				for _,v in ipairs(t) do
					SML:Register(m, v[1], v[2])
				end
			end
		end
	end
end

Aijson.frame = CreateFrame("Frame")
Aijson.frame:SetScript("OnEvent", Aijson.OnEvent)
Aijson.frame:RegisterEvent("ADDON_LOADED")


--[[

----
---- PLEASE READ BEFORE DOING ANYTHING ----
----

Only fonts should be added to this addon. If you wish to add textures, sounds, ... create your own addon or use an existing one if there is one.
All fonts must be able to display special characters such as é, è, à, ü, É, Ç, ... Remember that not all the users use the English client!

Don't add a font that you did not test. All fonts must be tested in game before upload.

Thanks for your cooperation! ;-)
pb_ee1

]]

-- registrations for media from the client itself belongs in LibSharedMedia-3.0

if not Aijson then return end

-- -----
-- FONT
-- -----

Aijson:Register("font", "Cantarell Bold", [[Interface\Addons\Aijson\Fonts\Cantarell-Bold.otf]])
Aijson:Register("font", "Cantarell ExtraBold", [[Interface\Addons\Aijson\Fonts\Cantarell-ExtraBold.otf]])
Aijson:Register("font", "Cantarell Light", [[Interface\Addons\Aijson\Fonts\Cantarell-Light.otf]])
Aijson:Register("font", "Cantarell Regular", [[Interface\Addons\Aijson\Fonts\Cantarell-Regular.otf]])
Aijson:Register("font", "Cantarell Thin", [[Interface\Addons\Aijson\Fonts\Cantarell-Thin.otf]])
Aijson:Register("font", "Cantarell VF", [[Interface\Addons\Aijson\Fonts\Cantarell-VF.otf]])

Aijson:Register("statusbar", "Flat", [[Interface\Addons\Aijson\Statusbar\flat.tga]])
Aijson:Register("statusbar", "MyBarForward", [[Interface\Addons\Aijson\Statusbar\mybar_forward.tga]])
Aijson:Register("statusbar", "MyBarReverse", [[Interface\Addons\Aijson\Statusbar\mybar_reverse.tga]])
Aijson:Register("statusbar", "TitanPanelBackgroundBottom", [[Interface\Addons\Aijson\Statusbar\TitanPanelBackgroundBottom0.tga]])
Aijson:Register("statusbar", "TitanPanelBackgroundTop", [[Interface\Addons\Aijson\Statusbar\TitanPanelBackgroundTop0.tga]])

Aijson:Register("sound", "Aijson, 10", [[Interface\Addons\Aijson\Sound\10.ogg]])
Aijson:Register("sound", "Aijson, 1", [[Interface\Addons\Aijson\Sound\1.ogg]])
Aijson:Register("sound", "Aijson, 2", [[Interface\Addons\Aijson\Sound\2.ogg]])
Aijson:Register("sound", "Aijson, 3", [[Interface\Addons\Aijson\Sound\3.ogg]])
Aijson:Register("sound", "Aijson, 4", [[Interface\Addons\Aijson\Sound\4.ogg]])
Aijson:Register("sound", "Aijson, 5", [[Interface\Addons\Aijson\Sound\5.ogg]])
Aijson:Register("sound", "Aijson, 6", [[Interface\Addons\Aijson\Sound\6.ogg]])
Aijson:Register("sound", "Aijson, 7", [[Interface\Addons\Aijson\Sound\7.ogg]])
Aijson:Register("sound", "Aijson, 8", [[Interface\Addons\Aijson\Sound\8.ogg]])
Aijson:Register("sound", "Aijson, 9", [[Interface\Addons\Aijson\Sound\9.ogg]])
Aijson:Register("sound", "Aijson, Add", [[Interface\Addons\Aijson\Sound\Add.ogg]])
Aijson:Register("sound", "Aijson, Adds", [[Interface\Addons\Aijson\Sound\Adds.ogg]])
Aijson:Register("sound", "Aijson, AMS", [[Interface\Addons\Aijson\Sound\AMS.ogg]])
Aijson:Register("sound", "Aijson, Ancestral Swiftness", [[Interface\Addons\Aijson\Sound\Ancestral Swiftness.ogg]])
Aijson:Register("sound", "Aijson, Anti-Magic Shell", [[Interface\Addons\Aijson\Sound\Anti-Magic Shell.ogg]])
Aijson:Register("sound", "Aijson, Arcane Power", [[Interface\Addons\Aijson\Sound\Arcane Power.ogg]])
Aijson:Register("sound", "Aijson, Arcane Torrent", [[Interface\Addons\Aijson\Sound\Arcane Torrent.ogg]])
Aijson:Register("sound", "Aijson, Archangel", [[Interface\Addons\Aijson\Sound\Archangel.ogg]])
Aijson:Register("sound", "Aijson, Ardent Defender", [[Interface\Addons\Aijson\Sound\Ardent Defender.ogg]])
Aijson:Register("sound", "Aijson, Asphyxiate", [[Interface\Addons\Aijson\Sound\Asphyxiate.ogg]])
Aijson:Register("sound", "Aijson, Avatar", [[Interface\Addons\Aijson\Sound\Avatar.ogg]])
Aijson:Register("sound", "Aijson, Avenging Wrath", [[Interface\Addons\Aijson\Sound\Avenging Wrath.ogg]])
Aijson:Register("sound", "Aijson, Avert Harm", [[Interface\Addons\Aijson\Sound\Avert Harm.ogg]])
Aijson:Register("sound", "Aijson, Avoid", [[Interface\Addons\Aijson\Sound\Avoid.ogg]])
Aijson:Register("sound", "Aijson, Backup", [[Interface\Addons\Aijson\Sound\Backup.ogg]])
Aijson:Register("sound", "Aijson, Bait", [[Interface\Addons\Aijson\Sound\Bait.ogg]])
Aijson:Register("sound", "Aijson, Barkskin", [[Interface\Addons\Aijson\Sound\Barkskin.ogg]])
Aijson:Register("sound", "Aijson, Beam", [[Interface\Addons\Aijson\Sound\Beam.ogg]])
Aijson:Register("sound", "Aijson, Be Aware", [[Interface\Addons\Aijson\Sound\Be Aware.ogg]])
Aijson:Register("sound", "Aijson, Behind", [[Interface\Addons\Aijson\Sound\Behind.ogg]])
Aijson:Register("sound", "Aijson, Berserking", [[Interface\Addons\Aijson\Sound\Berserking.ogg]])
Aijson:Register("sound", "Aijson, Blazing Speed", [[Interface\Addons\Aijson\Sound\Blazing Speed.ogg]])
Aijson:Register("sound", "Aijson, Blood Fury", [[Interface\Addons\Aijson\Sound\Blood Fury.ogg]])
Aijson:Register("sound", "Aijson, Bloodlust", [[Interface\Addons\Aijson\Sound\Bloodlust.ogg]])
Aijson:Register("sound", "Aijson, Blood Tap", [[Interface\Addons\Aijson\Sound\Blood Tap.ogg]])
Aijson:Register("sound", "Aijson, Blue", [[Interface\Addons\Aijson\Sound\Blue.ogg]])
Aijson:Register("sound", "Aijson, Bomb", [[Interface\Addons\Aijson\Sound\Bomb.ogg]])
Aijson:Register("sound", "Aijson, Bone Shield", [[Interface\Addons\Aijson\Sound\Bone Shield.ogg]])
Aijson:Register("sound", "Aijson, Boss Immune", [[Interface\Addons\Aijson\Sound\Boss Immune.ogg]])
Aijson:Register("sound", "Aijson, Bottom", [[Interface\Addons\Aijson\Sound\Bottom.ogg]])
Aijson:Register("sound", "Aijson, Break", [[Interface\Addons\Aijson\Sound\Break.ogg]])
Aijson:Register("sound", "Aijson, Break Tether", [[Interface\Addons\Aijson\Sound\Break Tether.ogg]])
Aijson:Register("sound", "Aijson, Brilliant Glass", [[Interface\Addons\Aijson\Sound\Brilliant Glass.ogg]])
Aijson:Register("sound", "Aijson, Buff", [[Interface\Addons\Aijson\Sound\Buff.ogg]])
Aijson:Register("sound", "Aijson, Call Dreadstalkers", [[Interface\Addons\Aijson\Sound\Call Dreadstalkers.ogg]])
Aijson:Register("sound", "Aijson, Cancel Cast", [[Interface\Addons\Aijson\Sound\Cancel Cast.ogg]])
Aijson:Register("sound", "Aijson, Capacitor Totem", [[Interface\Addons\Aijson\Sound\Capacitor Totem.ogg]])
Aijson:Register("sound", "Aijson, Cat Form", [[Interface\Addons\Aijson\Sound\Cat Form.ogg]])
Aijson:Register("sound", "Aijson, Caution", [[Interface\Addons\Aijson\Sound\Caution.ogg]])
Aijson:Register("sound", "Aijson, CC", [[Interface\Addons\Aijson\Sound\CC.ogg]])
Aijson:Register("sound", "Aijson, Centre", [[Interface\Addons\Aijson\Sound\Centre.ogg]])
Aijson:Register("sound", "Aijson, Chain", [[Interface\Addons\Aijson\Sound\Chain.ogg]])
Aijson:Register("sound", "Aijson, Charge", [[Interface\Addons\Aijson\Sound\Charge.ogg]])
Aijson:Register("sound", "Aijson, Cheap Shot", [[Interface\Addons\Aijson\Sound\Cheap Shot.ogg]])
Aijson:Register("sound", "Aijson, Chi Brew", [[Interface\Addons\Aijson\Sound\Chi Brew.ogg]])
Aijson:Register("sound", "Aijson, Chi Torpedo", [[Interface\Addons\Aijson\Sound\Chi Torpedo.ogg]])
Aijson:Register("sound", "Aijson, Circle", [[Interface\Addons\Aijson\Sound\Circle.ogg]])
Aijson:Register("sound", "Aijson, Circle on You", [[Interface\Addons\Aijson\Sound\Circle on You.ogg]])
Aijson:Register("sound", "Aijson, Clash", [[Interface\Addons\Aijson\Sound\Clash.ogg]])
Aijson:Register("sound", "Aijson, Cleansing Pain", [[Interface\Addons\Aijson\Sound\Cleansing Pain.ogg]])
Aijson:Register("sound", "Aijson, Clear", [[Interface\Addons\Aijson\Sound\Clear.ogg]])
Aijson:Register("sound", "Aijson, Cleave", [[Interface\Addons\Aijson\Sound\Cleave.ogg]])
Aijson:Register("sound", "Aijson, Cold Blood", [[Interface\Addons\Aijson\Sound\Cold Blood.ogg]])
Aijson:Register("sound", "Aijson, Cold Snap", [[Interface\Addons\Aijson\Sound\Cold Snap.ogg]])
Aijson:Register("sound", "Aijson, Collect", [[Interface\Addons\Aijson\Sound\Collect.ogg]])
Aijson:Register("sound", "Aijson, Combustion", [[Interface\Addons\Aijson\Sound\Combustion.ogg]])
Aijson:Register("sound", "Aijson, Completed", [[Interface\Addons\Aijson\Sound\Completed.ogg]])
Aijson:Register("sound", "Aijson, Counterspell", [[Interface\Addons\Aijson\Sound\Counterspell.ogg]])
Aijson:Register("sound", "Aijson, Crit Buff", [[Interface\Addons\Aijson\Sound\Crit Buff.ogg]])
Aijson:Register("sound", "Aijson, Cross", [[Interface\Addons\Aijson\Sound\Cross.ogg]])
Aijson:Register("sound", "Aijson, Cross on You", [[Interface\Addons\Aijson\Sound\Cross on You.ogg]])
Aijson:Register("sound", "Aijson, Cyclone", [[Interface\Addons\Aijson\Sound\Cyclone.ogg]])
Aijson:Register("sound", "Aijson, Dampen Harm", [[Interface\Addons\Aijson\Sound\Dampen Harm.ogg]])
Aijson:Register("sound", "Aijson, Dance", [[Interface\Addons\Aijson\Sound\Dance.ogg]])
Aijson:Register("sound", "Aijson, Dark Command", [[Interface\Addons\Aijson\Sound\Dark Command.ogg]])
Aijson:Register("sound", "Aijson, Darkmoon Card: Greatness", [[Interface\Addons\Aijson\Sound\Darkmoon Card: Greatness.ogg]])
Aijson:Register("sound", "Aijson, Dash", [[Interface\Addons\Aijson\Sound\Dash.ogg]])
Aijson:Register("sound", "Aijson, Deadly Calm", [[Interface\Addons\Aijson\Sound\Deadly Calm.ogg]])
Aijson:Register("sound", "Aijson, Death Grip", [[Interface\Addons\Aijson\Sound\Death Grip.ogg]])
Aijson:Register("sound", "Aijson, Debuff Avoid", [[Interface\Addons\Aijson\Sound\Debuff Avoid.ogg]])
Aijson:Register("sound", "Aijson, Debuff expired", [[Interface\Addons\Aijson\Sound\Debuff expired.ogg]])
Aijson:Register("sound", "Aijson, Debuff", [[Interface\Addons\Aijson\Sound\Debuff.ogg]])
Aijson:Register("sound", "Aijson, Desperate Prayer", [[Interface\Addons\Aijson\Sound\Desperate Prayer.ogg]])
Aijson:Register("sound", "Aijson, Deterrence", [[Interface\Addons\Aijson\Sound\Deterrence.ogg]])
Aijson:Register("sound", "Aijson, Devotion Aura", [[Interface\Addons\Aijson\Sound\Devotion Aura.ogg]])
Aijson:Register("sound", "Aijson, Diamond", [[Interface\Addons\Aijson\Sound\Diamond.ogg]])
Aijson:Register("sound", "Aijson, Diamond on You", [[Interface\Addons\Aijson\Sound\Diamond on You.ogg]])
Aijson:Register("sound", "Aijson, Diffuse Magic", [[Interface\Addons\Aijson\Sound\Diffuse Magic.ogg]])
Aijson:Register("sound", "Aijson, Dispell", [[Interface\Addons\Aijson\Sound\Dispell.ogg]])
Aijson:Register("sound", "Aijson, Divine Protection", [[Interface\Addons\Aijson\Sound\Divine Protection.ogg]])
Aijson:Register("sound", "Aijson, Divine Shield", [[Interface\Addons\Aijson\Sound\Divine Shield.ogg]])
Aijson:Register("sound", "Aijson, Dodge", [[Interface\Addons\Aijson\Sound\Dodge.ogg]])
Aijson:Register("sound", "Aijson, Dont Move", [[Interface\Addons\Aijson\Sound\Dont Move.ogg]])
Aijson:Register("sound", "Aijson, Dont Release", [[Interface\Addons\Aijson\Sound\Dont Release.ogg]])
Aijson:Register("sound", "Aijson, DPS Mind Controlled", [[Interface\Addons\Aijson\Sound\DPS Mind Controlled.ogg]])
Aijson:Register("sound", "Aijson, DPS", [[Interface\Addons\Aijson\Sound\DPS.ogg]])
Aijson:Register("sound", "Aijson, Dreadstalkers", [[Interface\Addons\Aijson\Sound\Dreadstalkers.ogg]])
Aijson:Register("sound", "Aijson, Dreamcloth", [[Interface\Addons\Aijson\Sound\Dreamcloth.ogg]])
Aijson:Register("sound", "Aijson, Drop Edges", [[Interface\Addons\Aijson\Sound\Drop Edges.ogg]])
Aijson:Register("sound", "Aijson, Drop", [[Interface\Addons\Aijson\Sound\Drop.ogg]])
Aijson:Register("sound", "Aijson, Edge", [[Interface\Addons\Aijson\Sounddge.ogg]])
Aijson:Register("sound", "Aijson, Eggs", [[Interface\Addons\Aijson\Soundggs.ogg]])
Aijson:Register("sound", "Aijson, Elemental Mastery", [[Interface\Addons\Aijson\Soundlemental Mastery.ogg]])
Aijson:Register("sound", "Aijson, Elune's Lantern", [[Interface\Addons\Aijson\Soundlune's Lantern.ogg]])
Aijson:Register("sound", "Aijson, Elusive Brew", [[Interface\Addons\Aijson\Soundlusive Brew.ogg]])
Aijson:Register("sound", "Aijson, Empower Rune Weapon", [[Interface\Addons\Aijson\Soundmpower Rune Weapon.ogg]])
Aijson:Register("sound", "Aijson, Energizing Brew", [[Interface\Addons\Aijson\Soundnergizing Brew.ogg]])
Aijson:Register("sound", "Aijson, Escort", [[Interface\Addons\Aijson\Soundscort.ogg]])
Aijson:Register("sound", "Aijson, Evasion", [[Interface\Addons\Aijson\Soundvasion.ogg]])
Aijson:Register("sound", "Aijson, Execute Mind Control", [[Interface\Addons\Aijson\Soundxecute Mind Control.ogg]])
Aijson:Register("sound", "Aijson, Execute", [[Interface\Addons\Aijson\Soundxecute.ogg]])
Aijson:Register("sound", "Aijson, Exit", [[Interface\Addons\Aijson\Soundxit.ogg]])
Aijson:Register("sound", "Aijson, F10", [[Interface\Addons\Aijson\Sound\F10.ogg]])
Aijson:Register("sound", "Aijson, F11", [[Interface\Addons\Aijson\Sound\F11.ogg]])
Aijson:Register("sound", "Aijson, F12", [[Interface\Addons\Aijson\Sound\F12.ogg]])
Aijson:Register("sound", "Aijson, F1", [[Interface\Addons\Aijson\Sound\F1.ogg]])
Aijson:Register("sound", "Aijson, F2", [[Interface\Addons\Aijson\Sound\F2.ogg]])
Aijson:Register("sound", "Aijson, F3", [[Interface\Addons\Aijson\Sound\F3.ogg]])
Aijson:Register("sound", "Aijson, F5", [[Interface\Addons\Aijson\Sound\F5.ogg]])
Aijson:Register("sound", "Aijson, F6", [[Interface\Addons\Aijson\Sound\F6.ogg]])
Aijson:Register("sound", "Aijson, F7", [[Interface\Addons\Aijson\Sound\F7.ogg]])
Aijson:Register("sound", "Aijson, F8", [[Interface\Addons\Aijson\Sound\F8.ogg]])
Aijson:Register("sound", "Aijson, F9", [[Interface\Addons\Aijson\Sound\F9.ogg]])
Aijson:Register("sound", "Aijson, Face Away", [[Interface\Addons\Aijson\Sound\Face Away.ogg]])
Aijson:Register("sound", "Aijson, Fade", [[Interface\Addons\Aijson\Sound\Fade.ogg]])
Aijson:Register("sound", "Aijson, Faerie Fire", [[Interface\Addons\Aijson\Sound\Faerie Fire.ogg]])
Aijson:Register("sound", "Aijson, Felguard", [[Interface\Addons\Aijson\Sound\Felguard.ogg]])
Aijson:Register("sound", "Aijson, Felguardrange", [[Interface\Addons\Aijson\Sound\Felguardrange.ogg]])
Aijson:Register("sound", "Aijson, Felhunterrange", [[Interface\Addons\Aijson\Sound\Felhunterrange.ogg]])
Aijson:Register("sound", "Aijson, Find Partner", [[Interface\Addons\Aijson\Sound\Find Partner.ogg]])
Aijson:Register("sound", "Aijson, Fixated", [[Interface\Addons\Aijson\Sound\Fixated.ogg]])
Aijson:Register("sound", "Aijson, Fixate", [[Interface\Addons\Aijson\Sound\Fixate.ogg]])
Aijson:Register("sound", "Aijson, Focus Add", [[Interface\Addons\Aijson\Sound\Focus Add.ogg]])
Aijson:Register("sound", "Aijson, Focus Adds", [[Interface\Addons\Aijson\Sound\Focus Adds.ogg]])
Aijson:Register("sound", "Aijson, Focus Boss", [[Interface\Addons\Aijson\Sound\Focus Boss.ogg]])
Aijson:Register("sound", "Aijson, Focusrange", [[Interface\Addons\Aijson\Sound\Focusrange.ogg]])
Aijson:Register("sound", "Aijson, Forbearance", [[Interface\Addons\Aijson\Sound\Forbearance.ogg]])
Aijson:Register("sound", "Aijson, Fortifying Brew", [[Interface\Addons\Aijson\Sound\Fortifying Brew.ogg]])
Aijson:Register("sound", "Aijson, Frenzied Regeneration", [[Interface\Addons\Aijson\Sound\Frenzied Regeneration.ogg]])
Aijson:Register("sound", "Aijson, Frontal 180", [[Interface\Addons\Aijson\Sound\Frontal 180.ogg]])
Aijson:Register("sound", "Aijson, Frontal Cone", [[Interface\Addons\Aijson\Sound\Frontal Cone.ogg]])
Aijson:Register("sound", "Aijson, Frontal", [[Interface\Addons\Aijson\Sound\Frontal.ogg]])
Aijson:Register("sound", "Aijson, Gate", [[Interface\Addons\Aijson\Sound\Gate.ogg]])
Aijson:Register("sound", "Aijson, Gather", [[Interface\Addons\Aijson\Sound\Gather.ogg]])
Aijson:Register("sound", "Aijson, Gift of the Naaru", [[Interface\Addons\Aijson\Sound\Gift of the Naaru.ogg]])
Aijson:Register("sound", "Aijson, Goodbye", [[Interface\Addons\Aijson\Sound\Goodbye.ogg]])
Aijson:Register("sound", "Aijson, Go to Circle", [[Interface\Addons\Aijson\Sound\Go to Circle.ogg]])
Aijson:Register("sound", "Aijson, Go to Cross", [[Interface\Addons\Aijson\Sound\Go to Cross.ogg]])
Aijson:Register("sound", "Aijson, Go to Diamond", [[Interface\Addons\Aijson\Sound\Go to Diamond.ogg]])
Aijson:Register("sound", "Aijson, Go to Moon", [[Interface\Addons\Aijson\Sound\Go to Moon.ogg]])
Aijson:Register("sound", "Aijson, Go to Skull", [[Interface\Addons\Aijson\Sound\Go to Skull.ogg]])
Aijson:Register("sound", "Aijson, Go to Square", [[Interface\Addons\Aijson\Sound\Go to Square.ogg]])
Aijson:Register("sound", "Aijson, Go to Star", [[Interface\Addons\Aijson\Sound\Go to Star.ogg]])
Aijson:Register("sound", "Aijson, Go to Triangle", [[Interface\Addons\Aijson\Sound\Go to Triangle.ogg]])
Aijson:Register("sound", "Aijson, Green", [[Interface\Addons\Aijson\Sound\Green.ogg]])
Aijson:Register("sound", "Aijson, Group 1", [[Interface\Addons\Aijson\Sound\Group 1.ogg]])
Aijson:Register("sound", "Aijson, Group 2", [[Interface\Addons\Aijson\Sound\Group 2.ogg]])
Aijson:Register("sound", "Aijson, Group 3", [[Interface\Addons\Aijson\Sound\Group 3.ogg]])
Aijson:Register("sound", "Aijson, Group 4", [[Interface\Addons\Aijson\Sound\Group 4.ogg]])
Aijson:Register("sound", "Aijson, Group 5", [[Interface\Addons\Aijson\Sound\Group 5.ogg]])
Aijson:Register("sound", "Aijson, Group A", [[Interface\Addons\Aijson\Sound\Group A.ogg]])
Aijson:Register("sound", "Aijson, Group B", [[Interface\Addons\Aijson\Sound\Group B.ogg]])
Aijson:Register("sound", "Aijson, Group C", [[Interface\Addons\Aijson\Sound\Group C.ogg]])
Aijson:Register("sound", "Aijson, Group D", [[Interface\Addons\Aijson\Sound\Group D.ogg]])
Aijson:Register("sound", "Aijson, Growl", [[Interface\Addons\Aijson\Sound\Growl.ogg]])
Aijson:Register("sound", "Aijson, Guarded by the Light", [[Interface\Addons\Aijson\Sound\Guarded by the Light.ogg]])
Aijson:Register("sound", "Aijson, Guardian of Ancient Kings", [[Interface\Addons\Aijson\Sound\Guardian of Ancient Kings.ogg]])
Aijson:Register("sound", "Aijson, Guardian Spirit", [[Interface\Addons\Aijson\Sound\Guardian Spirit.ogg]])
Aijson:Register("sound", "Aijson, Hammer of Justice", [[Interface\Addons\Aijson\Sound\Hammer of Justice.ogg]])
Aijson:Register("sound", "Aijson, Hamstring", [[Interface\Addons\Aijson\Sound\Hamstring.ogg]])
Aijson:Register("sound", "Aijson, Hand of Protection", [[Interface\Addons\Aijson\Sound\Hand of Protection.ogg]])
Aijson:Register("sound", "Aijson, Haste Buff", [[Interface\Addons\Aijson\Sound\Haste Buff.ogg]])
Aijson:Register("sound", "Aijson, Heal Cd", [[Interface\Addons\Aijson\Sound\Heal Cd.ogg]])
Aijson:Register("sound", "Aijson, Healer", [[Interface\Addons\Aijson\Sound\Healer.ogg]])
Aijson:Register("sound", "Aijson, Heal Pet", [[Interface\Addons\Aijson\Sound\Heal Pet.ogg]])
Aijson:Register("sound", "Aijson, Health Funnel", [[Interface\Addons\Aijson\Sound\Health Funnel.ogg]])
Aijson:Register("sound", "Aijson, Healthstone", [[Interface\Addons\Aijson\Sound\Healthstone.ogg]])
Aijson:Register("sound", "Aijson, Healthstone on Healer", [[Interface\Addons\Aijson\Sound\Healthstone on Healer.ogg]])
Aijson:Register("sound", "Aijson, Healthstone on Tank", [[Interface\Addons\Aijson\Sound\Healthstone on Tank.ogg]])
Aijson:Register("sound", "Aijson, Heroic Strike", [[Interface\Addons\Aijson\Sound\Heroic Strike.ogg]])
Aijson:Register("sound", "Aijson, Heroism", [[Interface\Addons\Aijson\Sound\Heroism.ogg]])
Aijson:Register("sound", "Aijson, Hero", [[Interface\Addons\Aijson\Sound\Hero.ogg]])
Aijson:Register("sound", "Aijson, Hex", [[Interface\Addons\Aijson\Sound\Hex.ogg]])
Aijson:Register("sound", "Aijson, Hide behind Pillar", [[Interface\Addons\Aijson\Sound\Hide behind Pillar.ogg]])
Aijson:Register("sound", "Aijson, Hide", [[Interface\Addons\Aijson\Sound\Hide.ogg]])
Aijson:Register("sound", "Aijson, High Energy", [[Interface\Addons\Aijson\Sound\High Energy.ogg]])
Aijson:Register("sound", "Aijson, High", [[Interface\Addons\Aijson\Sound\High.ogg]])
Aijson:Register("sound", "Aijson, High Stacks", [[Interface\Addons\Aijson\Sound\High Stacks.ogg]])
Aijson:Register("sound", "Aijson, High Threat", [[Interface\Addons\Aijson\Sound\High Threat.ogg]])
Aijson:Register("sound", "Aijson, Holy Avenger", [[Interface\Addons\Aijson\Sound\Holy Avenger.ogg]])
Aijson:Register("sound", "Aijson, Icebound Fortitude", [[Interface\Addons\Aijson\Sound\Icebound Fortitude.ogg]])
Aijson:Register("sound", "Aijson, Ice Floes", [[Interface\Addons\Aijson\Sound\Ice Floes.ogg]])
Aijson:Register("sound", "Aijson, Icy Prism", [[Interface\Addons\Aijson\Sound\Icy Prism.ogg]])
Aijson:Register("sound", "Aijson, Icy Veins", [[Interface\Addons\Aijson\Sound\Icy Veins.ogg]])
Aijson:Register("sound", "Aijson, Immune", [[Interface\Addons\Aijson\Sound\Immune.ogg]])
Aijson:Register("sound", "Aijson, Immunity", [[Interface\Addons\Aijson\Sound\Immunity.ogg]])
Aijson:Register("sound", "Aijson, Incapacitating Roar", [[Interface\Addons\Aijson\Sound\Incapacitating Roar.ogg]])
Aijson:Register("sound", "Aijson, Inner Focus", [[Interface\Addons\Aijson\Sound\Inner Focus.ogg]])
Aijson:Register("sound", "Aijson, Inner Rage", [[Interface\Addons\Aijson\Sound\Inner Rage.ogg]])
Aijson:Register("sound", "Aijson, In", [[Interface\Addons\Aijson\Sound\In.ogg]])
Aijson:Register("sound", "Aijson, Inside", [[Interface\Addons\Aijson\Sound\Inside.ogg]])
Aijson:Register("sound", "Aijson, Intermission", [[Interface\Addons\Aijson\Sound\Intermission.ogg]])
Aijson:Register("sound", "Aijson, Interrupt", [[Interface\Addons\Aijson\Sound\Interrupt.ogg]])
Aijson:Register("sound", "Aijson, Intervene", [[Interface\Addons\Aijson\Sound\Intervene.ogg]])
Aijson:Register("sound", "Aijson, Intimidation", [[Interface\Addons\Aijson\Sound\Intimidation.ogg]])
Aijson:Register("sound", "Aijson, Invisibility", [[Interface\Addons\Aijson\Sound\Invisibility.ogg]])
Aijson:Register("sound", "Aijson, Invoke Xuen, the White Tiger", [[Interface\Addons\Aijson\Sound\Invoke Xuen, the White Tiger.ogg]])
Aijson:Register("sound", "Aijson, Jump", [[Interface\Addons\Aijson\Sound\Jump.ogg]])
Aijson:Register("sound", "Aijson, Kick", [[Interface\Addons\Aijson\Sound\Kick.ogg]])
Aijson:Register("sound", "Aijson, Kidney Shot", [[Interface\Addons\Aijson\Sound\Kidney Shot.ogg]])
Aijson:Register("sound", "Aijson, Kill Command", [[Interface\Addons\Aijson\Sound\Kill Command.ogg]])
Aijson:Register("sound", "Aijson, Kite", [[Interface\Addons\Aijson\Sound\Kite.ogg]])
Aijson:Register("sound", "Aijson, Knock", [[Interface\Addons\Aijson\Sound\Knock.ogg]])
Aijson:Register("sound", "Aijson, Lay on Hands", [[Interface\Addons\Aijson\Sound\Lay on Hands.ogg]])
Aijson:Register("sound", "Aijson, Leap of Faith", [[Interface\Addons\Aijson\Sound\Leap of Faith.ogg]])
Aijson:Register("sound", "Aijson, Left", [[Interface\Addons\Aijson\Sound\Left.ogg]])
Aijson:Register("sound", "Aijson, Lichborne", [[Interface\Addons\Aijson\Sound\Lichborne.ogg]])
Aijson:Register("sound", "Aijson, Line of Sight", [[Interface\Addons\Aijson\Sound\Line of Sight.ogg]])
Aijson:Register("sound", "Aijson, Linked", [[Interface\Addons\Aijson\Sound\Linked.ogg]])
Aijson:Register("sound", "Aijson, Lock Gate", [[Interface\Addons\Aijson\Sound\Lock Gate.ogg]])
Aijson:Register("sound", "Aijson, Lock Rock", [[Interface\Addons\Aijson\Sound\Lock Rock.ogg]])
Aijson:Register("sound", "Aijson, Loose Stack", [[Interface\Addons\Aijson\Sound\Loose Stack.ogg]])
Aijson:Register("sound", "Aijson, Low Health", [[Interface\Addons\Aijson\Sound\Low Health.ogg]])
Aijson:Register("sound", "Aijson, Low Mana", [[Interface\Addons\Aijson\Sound\Low Mana.ogg]])
Aijson:Register("sound", "Aijson, Low", [[Interface\Addons\Aijson\Sound\Low.ogg]])
Aijson:Register("sound", "Aijson, Low Sanity", [[Interface\Addons\Aijson\Sound\Low Sanity.ogg]])
Aijson:Register("sound", "Aijson, Low Threat", [[Interface\Addons\Aijson\Sound\Low Threat.ogg]])
Aijson:Register("sound", "Aijson, Maim", [[Interface\Addons\Aijson\Sound\Maim.ogg]])
Aijson:Register("sound", "Aijson, Major Healing Potion", [[Interface\Addons\Aijson\Sound\Major Healing Potion.ogg]])
Aijson:Register("sound", "Aijson, Maul", [[Interface\Addons\Aijson\Sound\Maul.ogg]])
Aijson:Register("sound", "Aijson, Melee", [[Interface\Addons\Aijson\Sound\Melee.ogg]])
Aijson:Register("sound", "Aijson, Might of Ursoc", [[Interface\Addons\Aijson\Sound\Might of Ursoc.ogg]])
Aijson:Register("sound", "Aijson, Mighty Bash", [[Interface\Addons\Aijson\Sound\Mighty Bash.ogg]])
Aijson:Register("sound", "Aijson, Mind Control", [[Interface\Addons\Aijson\Sound\Mind Control.ogg]])
Aijson:Register("sound", "Aijson, Mind Freeze", [[Interface\Addons\Aijson\Sound\Mind Freeze.ogg]])
Aijson:Register("sound", "Aijson, Mines", [[Interface\Addons\Aijson\Sound\Mines.ogg]])
Aijson:Register("sound", "Aijson, Minor Inscription Research", [[Interface\Addons\Aijson\Sound\Minor Inscription Research.ogg]])
Aijson:Register("sound", "Aijson, Misdirect", [[Interface\Addons\Aijson\Sound\Misdirect.ogg]])
Aijson:Register("sound", "Aijson, Moon", [[Interface\Addons\Aijson\Sound\Moon.ogg]])
Aijson:Register("sound", "Aijson, Moon on You", [[Interface\Addons\Aijson\Sound\Moon on You.ogg]])
Aijson:Register("sound", "Aijson, Mortal Coil", [[Interface\Addons\Aijson\Sound\Mortal Coil.ogg]])
Aijson:Register("sound", "Aijson, Move Apart", [[Interface\Addons\Aijson\Sound\Move Apart.ogg]])
Aijson:Register("sound", "Aijson, Move as One", [[Interface\Addons\Aijson\Sound\Move as One.ogg]])
Aijson:Register("sound", "Aijson, Move Far", [[Interface\Addons\Aijson\Sound\Move Far.ogg]])
Aijson:Register("sound", "Aijson, Move Max Range", [[Interface\Addons\Aijson\Sound\Move Max Range.ogg]])
Aijson:Register("sound", "Aijson, Move", [[Interface\Addons\Aijson\Sound\Move.ogg]])
Aijson:Register("sound", "Aijson, Move Out", [[Interface\Addons\Aijson\Sound\Move Out.ogg]])
Aijson:Register("sound", "Aijson, Move Together", [[Interface\Addons\Aijson\Sound\Move Together.ogg]])
Aijson:Register("sound", "Aijson, Mr. Pinchy", [[Interface\Addons\Aijson\Sound\Mr. Pinchy.ogg]])
Aijson:Register("sound", "Aijson, Nature's Grasp", [[Interface\Addons\Aijson\Sound\Nature's Grasp.ogg]])
Aijson:Register("sound", "Aijson, Nature's Swiftness", [[Interface\Addons\Aijson\Sound\Nature's Swiftness.ogg]])
Aijson:Register("sound", "Aijson, Next", [[Interface\Addons\Aijson\Sound\Next.ogg]])
Aijson:Register("sound", "Aijson, Northrend Alchemy Research", [[Interface\Addons\Aijson\Sound\Northrend Alchemy Research.ogg]])
Aijson:Register("sound", "Aijson, Northrend Inscription Research", [[Interface\Addons\Aijson\Sound\Northrend Inscription Research.ogg]])
Aijson:Register("sound", "Aijson, Now", [[Interface\Addons\Aijson\Sound\Now.ogg]])
Aijson:Register("sound", "Aijson, Ocean", [[Interface\Addons\Aijson\Sound\Ocean.ogg]])
Aijson:Register("sound", "Aijson, Orange", [[Interface\Addons\Aijson\Sound\Orange.ogg]])
Aijson:Register("sound", "Aijson, Orb", [[Interface\Addons\Aijson\Sound\Orb.ogg]])
Aijson:Register("sound", "Aijson, Out", [[Interface\Addons\Aijson\Sound\Out.ogg]])
Aijson:Register("sound", "Aijson, Outside", [[Interface\Addons\Aijson\Sound\Outside.ogg]])
Aijson:Register("sound", "Aijson, Overlap", [[Interface\Addons\Aijson\Sound\Overlap.ogg]])
Aijson:Register("sound", "Aijson, Pain Suppression", [[Interface\Addons\Aijson\Sound\Pain Suppression.ogg]])
Aijson:Register("sound", "Aijson, Pendulum of Telluric Currents", [[Interface\Addons\Aijson\Sound\Pendulum of Telluric Currents.ogg]])
Aijson:Register("sound", "Aijson, Personal", [[Interface\Addons\Aijson\Sound\Personal.ogg]])
Aijson:Register("sound", "Aijson, Pet Range", [[Interface\Addons\Aijson\Sound\Pet Range.ogg]])
Aijson:Register("sound", "Aijson, Phase 1", [[Interface\Addons\Aijson\Sound\Phase 1.ogg]])
Aijson:Register("sound", "Aijson, Phase 2", [[Interface\Addons\Aijson\Sound\Phase 2.ogg]])
Aijson:Register("sound", "Aijson, Phase 3", [[Interface\Addons\Aijson\Sound\Phase 3.ogg]])
Aijson:Register("sound", "Aijson, Phase 4", [[Interface\Addons\Aijson\Sound\Phase 4.ogg]])
Aijson:Register("sound", "Aijson, Phase 5", [[Interface\Addons\Aijson\Sound\Phase 5.ogg]])
Aijson:Register("sound", "Aijson, Pillar", [[Interface\Addons\Aijson\Sound\Pillar.ogg]])
Aijson:Register("sound", "Aijson, Poison", [[Interface\Addons\Aijson\Sound\Poison.ogg]])
Aijson:Register("sound", "Aijson, Pool", [[Interface\Addons\Aijson\Sound\Pool.ogg]])
Aijson:Register("sound", "Aijson, Pots", [[Interface\Addons\Aijson\Sound\Pots.ogg]])
Aijson:Register("sound", "Aijson, Power Infusion", [[Interface\Addons\Aijson\Sound\Power Infusion.ogg]])
Aijson:Register("sound", "Aijson, Power Word: Barrier", [[Interface\Addons\Aijson\Sound\Power Word: Barrier.ogg]])
Aijson:Register("sound", "Aijson, Preparation", [[Interface\Addons\Aijson\Sound\Preparation.ogg]])
Aijson:Register("sound", "Aijson, Pre Pot", [[Interface\Addons\Aijson\Sound\Pre Pot.ogg]])
Aijson:Register("sound", "Aijson, Presence of Mind", [[Interface\Addons\Aijson\Sound\Presence of Mind.ogg]])
Aijson:Register("sound", "Aijson, Provoke", [[Interface\Addons\Aijson\Sound\Provoke.ogg]])
Aijson:Register("sound", "Aijson, Prowl", [[Interface\Addons\Aijson\Sound\Prowl.ogg]])
Aijson:Register("sound", "Aijson, Psychic Horror", [[Interface\Addons\Aijson\Sound\Psychic Horror.ogg]])
Aijson:Register("sound", "Aijson, Puddle", [[Interface\Addons\Aijson\Sound\Puddle.ogg]])
Aijson:Register("sound", "Aijson, Pummel", [[Interface\Addons\Aijson\Sound\Pummel.ogg]])
Aijson:Register("sound", "Aijson, Purge", [[Interface\Addons\Aijson\Sound\Purge.ogg]])
Aijson:Register("sound", "Aijson, Purifying Brew", [[Interface\Addons\Aijson\Sound\Purifying Brew.ogg]])
Aijson:Register("sound", "Aijson, Purple", [[Interface\Addons\Aijson\Sound\Purple.ogg]])
Aijson:Register("sound", "Aijson, Rake", [[Interface\Addons\Aijson\Sound\Rake.ogg]])
Aijson:Register("sound", "Aijson, Ranged", [[Interface\Addons\Aijson\Sound\Ranged.ogg]])
Aijson:Register("sound", "Aijson, Ready", [[Interface\Addons\Aijson\Sound\Ready.ogg]])
Aijson:Register("sound", "Aijson, Rebuke", [[Interface\Addons\Aijson\Sound\Rebuke.ogg]])
Aijson:Register("sound", "Aijson, Recklessness", [[Interface\Addons\Aijson\Sound\Recklessness.ogg]])
Aijson:Register("sound", "Aijson, Red", [[Interface\Addons\Aijson\Sound\Red.ogg]])
Aijson:Register("sound", "Aijson, Reflecting Damage", [[Interface\Addons\Aijson\Sound\Reflecting Damage.ogg]])
Aijson:Register("sound", "Aijson, Ress Healer", [[Interface\Addons\Aijson\Sound\Ress Healer.ogg]])
Aijson:Register("sound", "Aijson, Ress", [[Interface\Addons\Aijson\Sound\Ress.ogg]])
Aijson:Register("sound", "Aijson, Ress Tank", [[Interface\Addons\Aijson\Sound\Ress Tank.ogg]])
Aijson:Register("sound", "Aijson, Righteous Fury", [[Interface\Addons\Aijson\Sound\Righteous Fury.ogg]])
Aijson:Register("sound", "Aijson, Right", [[Interface\Addons\Aijson\Sound\Right.ogg]])
Aijson:Register("sound", "Aijson, Roll", [[Interface\Addons\Aijson\Sound\Roll.ogg]])
Aijson:Register("sound", "Aijson, Roof Beams", [[Interface\Addons\Aijson\Sound\Roof Beams.ogg]])
Aijson:Register("sound", "Aijson, Rune Tap", [[Interface\Addons\Aijson\Sound\Rune Tap.ogg]])
Aijson:Register("sound", "Aijson, Sanity", [[Interface\Addons\Aijson\Sound\Sanity.ogg]])
Aijson:Register("sound", "Aijson, Savage Defense", [[Interface\Addons\Aijson\Sound\Savage Defense.ogg]])
Aijson:Register("sound", "Aijson, Scatter", [[Interface\Addons\Aijson\Sound\Scatter.ogg]])
Aijson:Register("sound", "Aijson, Self Cd", [[Interface\Addons\Aijson\Sound\Self Cd.ogg]])
Aijson:Register("sound", "Aijson, Shadowfury", [[Interface\Addons\Aijson\Sound\Shadowfury.ogg]])
Aijson:Register("sound", "Aijson, Shamanistic Rage", [[Interface\Addons\Aijson\Sound\Shamanistic Rage.ogg]])
Aijson:Register("sound", "Aijson, Share Absorb", [[Interface\Addons\Aijson\Sound\Share Absorb.ogg]])
Aijson:Register("sound", "Aijson, Share Damage", [[Interface\Addons\Aijson\Sound\Share Damage.ogg]])
Aijson:Register("sound", "Aijson, Share", [[Interface\Addons\Aijson\Sound\Share.ogg]])
Aijson:Register("sound", "Aijson, Share Soak", [[Interface\Addons\Aijson\Sound\Share Soak.ogg]])
Aijson:Register("sound", "Aijson, Shield Barrier", [[Interface\Addons\Aijson\Sound\Shield Barrier.ogg]])
Aijson:Register("sound", "Aijson, Shield Block", [[Interface\Addons\Aijson\Sound\Shield Block.ogg]])
Aijson:Register("sound", "Aijson, Shield of the Righteous", [[Interface\Addons\Aijson\Sound\Shield of the Righteous.ogg]])
Aijson:Register("sound", "Aijson, Shield Wall", [[Interface\Addons\Aijson\Sound\Shield Wall.ogg]])
Aijson:Register("sound", "Aijson, Shroud", [[Interface\Addons\Aijson\Sound\Shroud.ogg]])
Aijson:Register("sound", "Aijson, Side Beams", [[Interface\Addons\Aijson\Sound\Side Beams.ogg]])
Aijson:Register("sound", "Aijson, Side", [[Interface\Addons\Aijson\Sound\Side.ogg]])
Aijson:Register("sound", "Aijson, Signet of Expertise", [[Interface\Addons\Aijson\Sound\Signet of Expertise.ogg]])
Aijson:Register("sound", "Aijson, Silence", [[Interface\Addons\Aijson\Sound\Silence.ogg]])
Aijson:Register("sound", "Aijson, Silencing Shot", [[Interface\Addons\Aijson\Sound\Silencing Shot.ogg]])
Aijson:Register("sound", "Aijson, Skull Bash", [[Interface\Addons\Aijson\Sound\Skull Bash.ogg]])
Aijson:Register("sound", "Aijson, Skull", [[Interface\Addons\Aijson\Sound\Skull.ogg]])
Aijson:Register("sound", "Aijson, Skull on You", [[Interface\Addons\Aijson\Sound\Skull on You.ogg]])
Aijson:Register("sound", "Aijson, Snowmaster 9000", [[Interface\Addons\Aijson\Sound\Snowmaster 9000.ogg]])
Aijson:Register("sound", "Aijson, Soak", [[Interface\Addons\Aijson\Sound\Soak.ogg]])
Aijson:Register("sound", "Aijson, Solar Beam", [[Interface\Addons\Aijson\Sound\Solar Beam.ogg]])
Aijson:Register("sound", "Aijson, Solo", [[Interface\Addons\Aijson\Sound\Solo.ogg]])
Aijson:Register("sound", "Aijson, Soon", [[Interface\Addons\Aijson\Sound\Soon.ogg]])
Aijson:Register("sound", "Aijson, Soulburn", [[Interface\Addons\Aijson\Sound\Soulburn.ogg]])
Aijson:Register("sound", "Aijson, Spear Hand Strike", [[Interface\Addons\Aijson\Sound\Spear Hand Strike.ogg]])
Aijson:Register("sound", "Aijson, Speed of Light", [[Interface\Addons\Aijson\Sound\Speed of Light.ogg]])
Aijson:Register("sound", "Aijson, Spell Lock", [[Interface\Addons\Aijson\Sound\Spell Lock.ogg]])
Aijson:Register("sound", "Aijson, Spell Steal", [[Interface\Addons\Aijson\Sound\Spell Steal.ogg]])
Aijson:Register("sound", "Aijson, Spikes", [[Interface\Addons\Aijson\Sound\Spikes.ogg]])
Aijson:Register("sound", "Aijson, Spirit Shell", [[Interface\Addons\Aijson\Sound\Spirit Shell.ogg]])
Aijson:Register("sound", "Aijson, Spread", [[Interface\Addons\Aijson\Sound\Spread.ogg]])
Aijson:Register("sound", "Aijson, Sprint", [[Interface\Addons\Aijson\Sound\Sprint.ogg]])
Aijson:Register("sound", "Aijson, Square", [[Interface\Addons\Aijson\Sound\Square.ogg]])
Aijson:Register("sound", "Aijson, Square on You", [[Interface\Addons\Aijson\Sound\Square on You.ogg]])
Aijson:Register("sound", "Aijson, Stack behind Boss", [[Interface\Addons\Aijson\Sound\Stack behind Boss.ogg]])
Aijson:Register("sound", "Aijson, Stack beside Boss", [[Interface\Addons\Aijson\Sound\Stack beside Boss.ogg]])
Aijson:Register("sound", "Aijson, Stack", [[Interface\Addons\Aijson\Sound\Stack.ogg]])
Aijson:Register("sound", "Aijson, Stack on Healer", [[Interface\Addons\Aijson\Sound\Stack on Healer.ogg]])
Aijson:Register("sound", "Aijson, Stack on Melee", [[Interface\Addons\Aijson\Sound\Stack on Melee.ogg]])
Aijson:Register("sound", "Aijson, Stack on", [[Interface\Addons\Aijson\Sound\Stack on.ogg]])
Aijson:Register("sound", "Aijson, Stack on Ranged", [[Interface\Addons\Aijson\Sound\Stack on Ranged.ogg]])
Aijson:Register("sound", "Aijson, Stack on Tank", [[Interface\Addons\Aijson\Sound\Stack on Tank.ogg]])
Aijson:Register("sound", "Aijson, Stairs", [[Interface\Addons\Aijson\Sound\Stairs.ogg]])
Aijson:Register("sound", "Aijson, Star", [[Interface\Addons\Aijson\Sound\Star.ogg]])
Aijson:Register("sound", "Aijson, Star on You", [[Interface\Addons\Aijson\Sound\Star on You.ogg]])
Aijson:Register("sound", "Aijson, Stopcast", [[Interface\Addons\Aijson\Sound\Stopcast.ogg]])
Aijson:Register("sound", "Aijson, Stop Moving", [[Interface\Addons\Aijson\Sound\Stop Moving.ogg]])
Aijson:Register("sound", "Aijson, Stop", [[Interface\Addons\Aijson\Sound\Stop.ogg]])
Aijson:Register("sound", "Aijson, Storm", [[Interface\Addons\Aijson\Sound\Storm.ogg]])
Aijson:Register("sound", "Aijson, Strangulate", [[Interface\Addons\Aijson\Sound\Strangulate.ogg]])
Aijson:Register("sound", "Aijson, Suicide", [[Interface\Addons\Aijson\Sound\Suicide.ogg]])
Aijson:Register("sound", "Aijson, Survival Instincts", [[Interface\Addons\Aijson\Sound\Survival Instincts.ogg]])
Aijson:Register("sound", "Aijson, Sweeping Strikes", [[Interface\Addons\Aijson\Sound\Sweeping Strikes.ogg]])
Aijson:Register("sound", "Aijson, Switch", [[Interface\Addons\Aijson\Sound\Switch.ogg]])
Aijson:Register("sound", "Aijson, Switch to Adds", [[Interface\Addons\Aijson\Sound\Switch to Adds.ogg]])
Aijson:Register("sound", "Aijson, Switch to Boss", [[Interface\Addons\Aijson\Sound\Switch to Boss.ogg]])
Aijson:Register("sound", "Aijson, Switch to Circle", [[Interface\Addons\Aijson\Sound\Switch to Circle.ogg]])
Aijson:Register("sound", "Aijson, Switch to Cross", [[Interface\Addons\Aijson\Sound\Switch to Cross.ogg]])
Aijson:Register("sound", "Aijson, Switch to Diamond", [[Interface\Addons\Aijson\Sound\Switch to Diamond.ogg]])
Aijson:Register("sound", "Aijson, Switch to Moon", [[Interface\Addons\Aijson\Sound\Switch to Moon.ogg]])
Aijson:Register("sound", "Aijson, Switch to", [[Interface\Addons\Aijson\Sound\Switch to.ogg]])
Aijson:Register("sound", "Aijson, Switch to Skull", [[Interface\Addons\Aijson\Sound\Switch to Skull.ogg]])
Aijson:Register("sound", "Aijson, Switch to Square", [[Interface\Addons\Aijson\Sound\Switch to Square.ogg]])
Aijson:Register("sound", "Aijson, Switch to Star", [[Interface\Addons\Aijson\Sound\Switch to Star.ogg]])
Aijson:Register("sound", "Aijson, Switch to Triangle", [[Interface\Addons\Aijson\Sound\Switch to Triangle.ogg]])
Aijson:Register("sound", "Aijson, Tail Swipe", [[Interface\Addons\Aijson\Sound\Tail Swipe.ogg]])
Aijson:Register("sound", "Aijson, Tank", [[Interface\Addons\Aijson\Sound\Tank.ogg]])
Aijson:Register("sound", "Aijson, Tank Swap", [[Interface\Addons\Aijson\Sound\Tank Swap.ogg]])
Aijson:Register("sound", "Aijson, Targeted", [[Interface\Addons\Aijson\Sound\Targeted.ogg]])
Aijson:Register("sound", "Aijson, Target Range", [[Interface\Addons\Aijson\Sound\Target Range.ogg]])
Aijson:Register("sound", "Aijson, Taunt", [[Interface\Addons\Aijson\Sound\Taunt.ogg]])
Aijson:Register("sound", "Aijson, Temporal Shield", [[Interface\Addons\Aijson\Sound\Temporal Shield.ogg]])
Aijson:Register("sound", "Aijson, Tethered", [[Interface\Addons\Aijson\Sound\Tethered.ogg]])
Aijson:Register("sound", "Aijson, Threat", [[Interface\Addons\Aijson\Sound\Threat.ogg]])
Aijson:Register("sound", "Aijson, Thunder Focus Tea", [[Interface\Addons\Aijson\Sound\Thunder Focus Tea.ogg]])
Aijson:Register("sound", "Aijson, Thunderstorm", [[Interface\Addons\Aijson\Sound\Thunderstorm.ogg]])
Aijson:Register("sound", "Aijson, Tigereye Brew", [[Interface\Addons\Aijson\Sound\Tigereye Brew.ogg]])
Aijson:Register("sound", "Aijson, Tight Stack", [[Interface\Addons\Aijson\Sound\Tight Stack.ogg]])
Aijson:Register("sound", "Aijson, Titansteel Bar", [[Interface\Addons\Aijson\Sound\Titansteel Bar.ogg]])
Aijson:Register("sound", "Aijson, Top", [[Interface\Addons\Aijson\Sound\Top.ogg]])
Aijson:Register("sound", "Aijson, Transistion", [[Interface\Addons\Aijson\Sound\Transistion.ogg]])
Aijson:Register("sound", "Aijson, Transmute: Living Elements", [[Interface\Addons\Aijson\Sound\Transmute: Living Elements.ogg]])
Aijson:Register("sound", "Aijson, Triangle", [[Interface\Addons\Aijson\Sound\Triangle.ogg]])
Aijson:Register("sound", "Aijson, Triangle on You", [[Interface\Addons\Aijson\Sound\Triangle on You.ogg]])
Aijson:Register("sound", "Aijson, Turn Around", [[Interface\Addons\Aijson\Sound\Turn Around.ogg]])
Aijson:Register("sound", "Aijson, Turn", [[Interface\Addons\Aijson\Sound\Turn.ogg]])
Aijson:Register("sound", "Aijson, Typhoon", [[Interface\Addons\Aijson\Sound\Typhoon.ogg]])
Aijson:Register("sound", "Aijson, Use Cloak", [[Interface\Addons\Aijson\Sound\Use Cloak.ogg]])
Aijson:Register("sound", "Aijson, Use", [[Interface\Addons\Aijson\Sound\Use.ogg]])
Aijson:Register("sound", "Aijson, Vampiric Blood", [[Interface\Addons\Aijson\Sound\Vampiric Blood.ogg]])
Aijson:Register("sound", "Aijson, Vampiric Embrace", [[Interface\Addons\Aijson\Sound\Vampiric Embrace.ogg]])
Aijson:Register("sound", "Aijson, Vanish", [[Interface\Addons\Aijson\Sound\Vanish.ogg]])
Aijson:Register("sound", "Aijson, Void", [[Interface\Addons\Aijson\Sound\Void.ogg]])
Aijson:Register("sound", "Aijson, Void Shift", [[Interface\Addons\Aijson\Sound\Void Shift.ogg]])
Aijson:Register("sound", "Aijson, Void Sphere", [[Interface\Addons\Aijson\Sound\Void Sphere.ogg]])
Aijson:Register("sound", "Aijson, War Stomp", [[Interface\Addons\Aijson\Sound\War Stomp.ogg]])
Aijson:Register("sound", "Aijson, Wind Shear", [[Interface\Addons\Aijson\Sound\Wind Shear.ogg]])
Aijson:Register("sound", "Aijson, Word of Glory", [[Interface\Addons\Aijson\Sound\Word of Glory.ogg]])
Aijson:Register("sound", "Aijson, Wyvern Sting", [[Interface\Addons\Aijson\Sound\Wyvern Sting.ogg]])
Aijson:Register("sound", "Aijson, Yellow", [[Interface\Addons\Aijson\Sound\Yellow.ogg]])
Aijson:Register("sound", "Aijson, Zen Meditation", [[Interface\Addons\Aijson\Sound\Zen Meditation.ogg]])
